api:
  version: @project.version@
server:
  port: 8081
  servlet:
    contextPath: /marvel
spring:
  application:
    name: marvel-api
marvel-api:
  base-url: https://gateway.marvel.com:443/v1/public

api-keys:
  public: ${PUBLIC_KEY}
  private: ${PRIVATE_KEY}

openapi:
  title: Marvel API
  version: @project.version@
  description: Marvel API
messages:
  global: 'classpath:/messages/global'

