spring:
  application:
    name: marvel-api-gateway
marvel-api:
  base-url: https://gateway.marvel.com:443/v1/public

api-keys:
  public: ${PUBLIC_KEY}
  private: ${PRIVATE_KEY}

openapi:
  title: Marvel API Gateway
  version: @project.version@
  description: Marvel API Gateway
messages:
  global: 'classpath:/messages/global'

