api:
  version: @project.version@
server:
  port: 8080
  servlet:
    contextPath: /marvel
spring:
  application:
    name: marvel-api
marvel-api:
  base-url: https://gateway.marvel.com:443/v1/public
translation-api:
  base-url: https://api.cognitive.microsofttranslator.com

api-keys:
  public: ${PUBLIC_KEY}
  private: ${PRIVATE_KEY}

translation-api-auth:
  key: ${TRANSLATION_API_KEY}
  region: ${TRANSLATION_API_REGION}

openapi:
  title: Marvel API Gateway
  version: @project.version@
  description: Marvel API Gateway

